# Generated by Django 3.2.7 on 2021-09-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210909_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='adress',
        ),
    ]
